# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'PokemonListApp' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for PokemonListApp
  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire', '~> 4.7'
end
